### ISSUE TITLE
Thank you very much.  I can not find your article!

### ISSUE THREAD

**Issue by suan12** [Baijianlu/mDCThermalC#1]

**Comment by yw-fang** [comment]
@suan12  Hi, I advise you to leave an email address on your profile of Github, otherwise other users or code developers cannot contact you directly. This is why I have to reply to you in this issue.
I contact you for other issue associated with other code, but not for this repo. (on the other hand, although the author of **mDCThermalC** didn't reply to you, I can answer you that the doi Baijianlu mentioned wasn't an article on a journal. First please paste "http://doi.org/10.5281/zenodo.2617208" to your browser, and you will find it's just a platform used for sharing data, but it will provide the authors a doi so that others can cite their work/code/data)

I am contacting you to send you a gentle reminder. I noted you forked the repo. **vasp-constrmag.F** from Leo Ma. However, I found this code violets the VASP copyright. I have told Leo in this afternoon, and he have already deleted it several hours ago. **Please delete the repo. from your Github page as soon as possible**. You can keep the source code in your local computer (you can also cite Leo's work if you use this function in your real research), but don't distribute it through internet, otherwise you may bring some troubles to yourself if VASP team finds your repo. on Github because it's illegal and not allowed by the copyright law.

**Comment by suan12** [comment]
I have already deleted vasp-constrmag.F.

**Comment by yw-fang** [comment]
@suan12 That's good! Thanks very much for your cooperations.
